# Generated by Django 4.0 on 2022-01-18 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='71 brick', max_length=300)),
                ('email', models.EmailField(default='uyiplay44@hotmail.com', max_length=300)),
                ('age', models.IntegerField(default=1)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Lead.user')),
            ],
        ),
    ]
